
// Publish speeding violation
POST http://127.0.0.1:6000/cjib/speedingviolation
Content-Type: application/json

{ "vehicleId": "RK-546-V", "roadId": "A12", "violationInKmh": 15 }

###

// Get vehicle info by license-number
GET http://127.0.0.1:6000/rdw/vehicle/KT-49-VV
