---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: trafficcontrol-secrets
  namespace: dapr-trafficcontrol
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ../dapr/components/secrets.json
    - name: nestedSeparator
      value: "."
scopes:
  - trafficcontrolservice
  - finecollectionservice
