---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-trafficcontrol
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ../../deployment/local/dapr/config/secrets.json
    - name: nestedSeparator
      value: "."
scopes:
  - finecollectionservice
