---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: exitcam
  namespace: dapr-trafficcontrol
spec:
  type: bindings.mqtt
  version: v1
  metadata:
    - name: url
      value: mqtt://localhost:1883
    - name: topic
      value: trafficcontrol/exitcam
    - name: consumerID
      value: "{uuid}"
scopes:
  - trafficcontrolservice
